### ISSUE TITLE
Typo raises warning: Possible misuse of comma operator here

### ISSUE THREAD

**Issue by ffAudio** [steinbergmedia/vst3_public_sdk#1]
https://github.com/steinbergmedia/vst3_public_sdk/blob/2841d355740be7770fd0ce61bc14a591d3981c14/source/vst/vstcomponentbase.cpp#L111

...I assume, there is a semicolon intended...

Cheers,
Daniel

**Comment by lmdsp** [comment]
Yes, I noticed that too when switching to XCode 9.
I've checked the standard and from what I gathered the actual behavior should be the same as if there were a semicolon. Probably still a good idea for Steinberg to fix it though.

**Comment by ygrabit** [comment]
fixed in VST3.6.8
