### ISSUE TITLE
Changing the preset should not affect the host bypass state in AAX

### ISSUE THREAD

**Issue by raygit83** [steinbergmedia/vst3_public_sdk#11]
Please check this short screencast:

[https://i.imgur.com/XmYdIhU.gif](url)

This is a demonstration of how the bypass is supposed to react when the user changes the presets in Pro Tools - check the Avid EQ-3 plugin as a reference.

The Fuse Audio Labs VQA-154 plugin uses Steinberg's AAX Wrapper and you can see that changing the presets overwrites the master bypass because it's stored in the plugin's state chunk.

I suggest using something along the lines of the following code in order to restore the bypass to its last setting once the preset is changed to overcome this:

1. Add a double member, e.g. "savedBypass" to the AAXWrapper class.

2. In AAXWrapper_Parameters::NotificationReceived() add

````
{
	char bypassId[10];
	sprintf(bypassId, "p%8X", mWrapper->mBypassParameterID);

	double value;

	if(GetParameterNormalizedValue(bypassId, &value) == AAX_SUCCESS)
		mWrapper->savedBypass = value;
	...
	break;
}
````

to the case AAX_eNotificationEvent_PresetOpened.

3. In AAXWrapper::onTimer() add

````
	char bypassId[10];
	sprintf(bypassId, "p%8X", mBypassParameterID);

	if(presetChanged)
	{
		int i = 0;
		double value;
		AAX_CString id;

		while(aaxParams->GetParameterIDFromIndex(i++, &id) == AAX_SUCCESS)
		{
			if(id == bypassId)
			{
				aaxParams->SetParameterNormalizedValue(id.CString(), savedBypass);
			}
			else if(aaxParams->GetParameterNormalizedValue(id.CString(), &value) == AAX_SUCCESS)
			{
				aaxParams->SetParameterNormalizedValue(id.CString(), value);
			}
		}

		presetChanged = false;
	}
````

to the recently added fix for "Automation issues after switching presets in aaxwrapper".

**Comment by ygrabit** [comment]
ok, thanks, i will add this special handling in the next update...

**Comment by raygit83** [comment]
Great! Thank You.
