### ISSUE TITLE
HostAttributeList::getString() does not put the terminating null character.

### ISSUE THREAD

**Issue by abique** [steinbergmedia/vst3_public_sdk#12]
https://github.com/steinbergmedia/vst3_public_sdk/blob/ced72c00d5c1365a4cca16cdbfb871be2496848b/source/vst/hosting/hostclasses.cpp#L301

**Comment by abique** [comment]
If `it->second->stringValue (stringSize)` includes the terminating 0, then I'm wrong.

**Comment by abique** [comment]
I suggest to add: `string[std::min<uint32> (stringSize, size - 1)] = 0;` after the memcpy().

**Comment by ygrabit** [comment]
HostAttributeList::setString...  should be used with null-terminated string...so no more handling needed
