### ISSUE TITLE
Incorrect size is passed (256) while it should be 128 characters right?

### ISSUE THREAD

**Issue by abique** [steinbergmedia/vst3_public_sdk#13]
https://github.com/steinbergmedia/vst3_public_sdk/blob/ced72c00d5c1365a4cca16cdbfb871be2496848b/samples/vst/hostchecker/source/hostcheckercontroller.cpp#L655

**Comment by abique** [comment]
Hi,
Still no comment on this one?
Alex.

**Comment by ygrabit** [comment]
getString request a sizeInBytes (see updated interface naming)
