### ISSUE TITLE
3.7.1_build_50 fails to build due to vstvalidator

### ISSUE THREAD

**Issue by dvzrv** [steinbergmedia/vst3_public_sdk#22]
Hi! I'm packaging vst3sdk for Arch Linux and for integration purposes I also build the example plugins.

Whereas this worked fine with the previous version (aside from #20 ) with `3.7.1_build_50` it is now broken:

```
  export CFLAGS+=" -DNDEBUG"
  export CXXFLAGS+=" -DNDEBUG"
  cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE='None' \
        -Wno-dev \
        -B build \
        -S .
  make VERBOSE=1 -C build
```

It seems that the validator is not called correctly.

The full build log is attached: 
[vst3sdk-3.7.1_build_50.log](https://github.com/steinbergmedia/vst3_public_sdk/files/5553451/vst3sdk-3.7.1_build_50.log)

**Comment by ygrabit** [comment]
why do specify  -DCMAKE_BUILD_TYPE='None'  ?

**Comment by dvzrv** [comment]
Because ['Release' overrides our default optimization flags](https://wiki.archlinux.org/index.php/CMake_package_guidelines#CMake_can_automatically_override_the_default_compiler_optimization_flag).

**Comment by ygrabit** [comment]
The problem is here that our cmakes need to have Debug or Release as Build Type....
