### ISSUE TITLE
Incorrect string copy in HostAttributeList::getString 

### ISSUE THREAD

**Issue by NBorthwick** [steinbergmedia/vst3_public_sdk#24]
In HostAttributeList::getString stringSize should be multiplied by sizeof TChar because it is copying bytes not characters.
This causes many plugins to display garbage in channel names when they query for attributes in response to Vst::ChannelContext::IInfoListener
Also plugins that use strings with HostAttributeList fail.

This is the fix.
https://github.com/steinbergmedia/vst3_public_sdk/pull/23

**Comment by ygrabit** [comment]
fixed in next update
