### ISSUE TITLE
Validator gives incorrect "Valid State Transition" test failure if plugin does not support 32bit samples

### ISSUE THREAD

**Issue by mikeoliphant** [steinbergmedia/vst3_public_sdk#26]
The validator application's "Valid State Transition" test is done using a 32bit sample configuration even if the plugin has reported that it only supports 64bit samples. This results in an incorrect test error when setupProcessing returns kResultFalse.

Instead, the test should be done with a 64bit sample configuration if that is the only configuration the plugin supports.

**Comment by ygrabit** [comment]
//------------------------------------------------------------------------
bool PLUGIN_API ValidStateTransitionTest::run (ITestResult* testResult)
{
	if (!testResult || !vstPlug || !audioEffect)
		return false;

	printTestHeader (testResult);
	if (!canProcessSampleSize (testResult))
		return true;

the added check canProcessSampleSize will avoid to mark the test as failure when not supported SampleSize.
Part of the next SDK update

**Comment by mikeoliphant** [comment]
Thanks!
