### ISSUE TITLE
Does not build after the GCC 11 update

### ISSUE THREAD

**Issue by jpcima** [steinbergmedia/vst3_public_sdk#32]
The error is raised from `public.sdk/source/main/moduleinit.h`.
`no member named 'numeric_limits' in namespace 'std'`
Including `<limits>` fixes this problem.

**Comment by ygrabit** [comment]
Thanks will be integrated in the next update

**Comment by jpcima** [comment]
Thanks you. Still regarding headers. is possible to change one of Win32 includes to lowercase?
It's one that the mingw cross-compile has issue with.
`source/vst/hosting/module_win32.cpp:#include <ShlObj.h>`

**Comment by ygrabit** [comment]
will do...

**Comment by scheffle** [comment]
Done!
