### ISSUE TITLE
CMake fails with Unknown CMake command "smtg_setup_universal_binary"

### ISSUE THREAD

**Issue by jamiebullock** [steinbergmedia/vst3_public_sdk#33]
Building on Ubuntu Linux with the latest git sources. I do the following:

> mkdir build
> cd build
> cmake ..

This gives the following error:

> CMake Error at CMakeLists.txt:46 (smtg_setup_universal_binary):
> Unknown CMake command "smtg_setup_universal_binary".

**Comment by scheffle** [comment]
Not enough information. See https://github.com/steinbergmedia/vst3sdk on how to compile the SDK.

**Comment by rramillien** [comment]
Just to reply with more detail. I've got the same issue with "smtg_target_setup_universal_binary".
It is caused when building the pluginterfaces only to not have to use the whole SDK.
pluginterfaces is the API and should be autonomous and not depend on its implementation.
