### ISSUE TITLE
VST_SDK is not set by any cmake files, and causes issues

### ISSUE THREAD

**Issue by etheory** [steinbergmedia/vst3_public_sdk#36]
https://github.com/steinbergmedia/vst3_public_sdk/blob/9589800ed94573354bc29de45eec5744523fbfcb/CMakeLists.txt#L28-L34

Hi there,

I've been trying to get the vstsdk3 to build a custom plugin, and the complete lack of decent documentation makes this a challenge.

I get the following error:
`[build]   Cannot find source file:
[build] 
[build]     source/common/pvaluecontainer.cpp`

Which is due to the above lines, because this file simply is not present in the repository, so this line looks to be an error with the library configuration. Where is this file? Why is it referenced when it doesn't exist?

If I add:
`set(VST_SDK on)`

to my build, it gets further, failing on:
`[build] LINK : fatal error LNK1181: cannot open input file 'pluginterfaces.lib'`

Is anyone else having these issues? Is there any decent documentation for the api for someone getting started with it that FULLY explains how to use it?

regards,
etheory

**Comment by scheffle** [comment]
See https://github.com/steinbergmedia/vst3sdk on how to use the SDK. This repository is just a part of the whole thing.
