### ISSUE TITLE
AU wrapper noteOff uses noteOn from union to write data

### ISSUE THREAD

**Issue by basdp** [steinbergmedia/vst3_public_sdk#38]
See this line:
https://github.com/steinbergmedia/vst3_public_sdk/blob/bc459feee68803346737901471441fd4829ec3f9/source/vst/auwrapper/auwrapper.mm#L1908

Is this intentional? I would have expected the code to be `e.noteOff.pitch = pitch;` and such.

Kind regards,

Bas

**Comment by ygrabit** [comment]
NoteOff is better for the reading, but it should not make any difference, these 2 Events noteOn and noteOff are an union.
We will change it,
