### ISSUE TITLE
Support for loading VST2 ?

### ISSUE THREAD

**Issue by jcelerier** [steinbergmedia/vst3_public_sdk#4]
Hello,

there are some bits of code : 

https://github.com/steinbergmedia/vst3_pluginterfaces/blob/master/vst/ivsthostapplication.h#L60
https://github.com/steinbergmedia/vst3_public_sdk/tree/master/source/vst/vst2wrapper

that seem to point to a compatibility with VST2, but the idea seems to be to wrap VST3 plug-ins behind the VST2 api if I'm not mistaken.

Is the reverse case also possible ? (eg loading VST2 plug-ins with the present SDK) ?

**Comment by ygrabit** [comment]
No, this is for wrapping a VST3 plugin into a VST2 for old host supporting only VST2
