### ISSUE TITLE
AUv3Wrapper resets all parameter values when `restartComponent(kParamTitlesChanged)` is called

### ISSUE THREAD

**Issue by nickdowell** [steinbergmedia/vst3_public_sdk#45]
The AUv3Wrapper's implementation of `ComponentHelper::restartComponent (int32 flags)` calls `[auv3Wrapper initializeParameters]` when the `kParamTitlesChanged` flag is set.

This unexpectedly causes all parameter values to be set to their default values because of the following code in `createParameters`: https://github.com/steinbergmedia/vst3_public_sdk/blob/55d7ed3c6a25496b41fc4440aaad4fae1b967d37/source/vst/auv3wrapper/Shared/AUv3Wrapper.mm#L1443-L1445

This is a major problem for plugins that call `restartComponent` with `kParamTitlesChanged` during preset loading.

I'm not sure what the correct solution is. Perhaps `createParameters` should not be calling `setParameter` or `setControllerParameter` and doing `sPar.value = _editcontroller->getParamNormalized(pi.id);` instead - or maybe the behaviour needs to switch depending on whether the is parameter is being initialised for the first time or not.

**Comment by scheffle** [comment]
Hi @nickdowell ,
can you check the attached update to the wrapper code if it fixes your issue?

[AUV3Wrapper.zip](https://github.com/steinbergmedia/vst3_public_sdk/files/10401816/AUV3Wrapper.zip)

If it does we will add this fix to the next SDK update.

**Comment by nickdowell** [comment]
Hi @scheffle your updated wrapper code works for me 👍 

In my own copy I had completely removed the calls to `setParameter:value:` and `setControllerParameter:value:` because it doesn't seem necessary to modify the parameter values when initialising the wrapper, and the AUv2 wrapper doesn't do this! 🤷

**Comment by nickdowell** [comment]
Closing because the issue is now resolved.
