### ISSUE TITLE
Allow moduleinfo.json and IPluginCompatibility to coexist

### ISSUE THREAD

**Issue by reuk** [steinbergmedia/vst3_public_sdk#63]
In JUCE, we implement the IPluginCompatibility interface, and then query this implementation during the plugin build to generate the moduleinfo.json.

However, plugins implemented in this way fail in the VST3 validator: https://github.com/steinbergmedia/vst3_public_sdk/blob/3a5e45d8089b5f34789fb68c7d174daa18caafba/source/vst/testsuite/general/plugcompat.cpp#L69-L81

The requirement that IPluginCompatibility and moduleinfo.json may not coexist is not mentioned in the [documentation](https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/Change+History/3.7.5/ModuleInfo.html) for the moduleinfo feature. As such, the inclusion of this check in the validator is unexpected.

Allowing the IPluginCompatibility interface to coexist with moduleinfo.json has a number of benefits:
- It allows plugin vendors to specify compatibility information in a single location, directly in their source code. This is much more intuitive and easier to implement than requiring that users supply this information to whatever build system they are using.
- It means that users need to supply *less* information overall. The plugin already knows its own class UIDs, so it can automatically insert these into the generated JSON. There's no need for users to find out this information themselves and supply it to the build system.
- It's consistent with the rest of the information in moduleinfo.json - all the rest of the information in this file can be derived from information that is already present in the VST3 dylib (the main role of the moduleinfotool is to format information present in a plugin binary into a moduleinfo.json for that binary!).

At the same time, I can't really think of any disadvantages of this approach. One possible argument is that duplicating information in two locations may lead to hosts inconsistently preferring one of those information sources. However, this is a problem even without considering IPluginCompatibility: all the rest of the information in moduleinfo.json is derived from the plugin binary, so it must *already* be specified that hosts should prefer to use the moduleinfo.json (if it exists) as the source of truth for any duplicated information. Therefore, allowing the moduleinfo.json to coexist with IPluginCompatibility does not place any additional implementation burden on hosts.

I hope that this requirement can be relaxed and the validator updated in the next version of the SDK.

A related change has previously been discussed [here](https://github.com/steinbergmedia/vst3_public_sdk/pull/53#issuecomment-1612742835).

Issue reports from our users are [here](https://github.com/juce-framework/JUCE/commit/06a2089872905242ead2fc0d4c31cf5c0cea8cc5) and [here](https://forum.juce.com/t/juce-7-0-6-vst3-dont-pass-vst3-sdk-validator-anymore/57481).

**Comment by ygrabit** [comment]
We still recommend to have only one (json or Interface)... we will change the error to a warning

**Comment by reuk** [comment]
Thanks, that's great news!

**Comment by bsangston** [comment]
Was just testing this out with the recent VST 3.7.9 branch update and I'm still experiencing issues with the validator as a JUCE user. Can move this over to a JUCE forum if it becomes more appropriate.

When testing the 3.7.9 validator against plugins built with 3.7.8 via JUCE, the validation still fails. I see the change in the printout of the moduleinfo.json warning vs error. But getCompatibilityJSON is called immediately after and still fails, so that behavior does not seem to have changed.

```
Warning: The module contains a moduleinfo.json file and the module factory exports a IPluginCompatibility class. The moduleinfo.json one is preferred.
Error: Call to IPluginCompatiblity::getCompatibilityJSON (IBStream*) failed
```

Is this expected?

**Comment by scheffle** [comment]
This error means that the call to getCompatibilityJSON(..) returns an error. So this looks like a JUCE issue to me.

**Comment by reuk** [comment]
The docs for getCompatibilityJSON say:
```
@return kResultTrue on success
```
which implies that the function may also fail and return kResultFalse - but not that a failure is equivalent to an error condition. In JUCE, we return false if there are no compatible classes. Would it be more correct to return true and to write an empty JSON array to the output stream?

Whichever approach is correct, I'd suggest that the docs are updated with more detail, because the API is ambiguous at the moment.

**Comment by scheffle** [comment]
OK, noted. 
The idea here is that this interface is not even exposed if there's no such functionality needed by the plug-in. It's just waste of energy and size if you do this for all plug-ins while only a hand full need to supply this information. Please change your implementation in JUCE, thanks.
