### ISSUE TITLE
undefined behavior - load of misaligned address

### ISSUE THREAD

**Issue by 0ax1** [steinbergmedia/vst3_public_sdk#64]
When running the VST3 validator with [UBSan](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) enabled, a load of a misaligned address address is flagged: 

```
vst3sdk/public.sdk/source/vst/hosting/../utility/uid.h:177:10: runtime error: load of misaligned address 0x00016f3ced7e for type 'const uint64_t' (aka 'const unsigned long long'), which requires 8 byte alignment
0x00016f3ced7e: note: pointer points here
 30 03 00 60 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  68 65 6c 70 00 00 00 00  24 fe
             ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior vst3sdk/public.sdk/source/vst/hosting/../utility/uid.h:177:10 in
vst3sdk/public.sdk/source/vst/hosting/../utility/uid.h:178:10: runtime error: load of misaligned address 0x00016f3ced86 for type 'const uint64_t' (aka 'const unsigned long long'), which requires 8 byte alignment
```

This is the case for lines 177 and 178 in uid.h:
- https://github.com/steinbergmedia/vst3_public_sdk/blob/master/source/vst/utility/uid.h?plain=1#L177
- https://github.com/steinbergmedia/vst3_public_sdk/blob/master/source/vst/utility/uid.h?plain=1#L178

**Comment by ygrabit** [comment]
Thanks, we will evaluate this and propose a fix for the next update...
