### ISSUE TITLE
Virtual function called from destructor

### ISSUE THREAD

**Issue by reuk** [steinbergmedia/vst3_public_sdk#70]
https://github.com/steinbergmedia/vst3_public_sdk/blob/3f20bcbf36283b1e5c450e088571be6226cd4e64/source/common/pluginview.cpp#L54

It's generally regarded to be a bad idea to call virtual functions from constructors and destructors. The Core Guidelines discussion on the topic can be found [here](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-ctor-virtual).

The highlighted line triggers the `clang-analyzer-optin.cplusplus.VirtualCall` clang-tidy check.

**Comment by ygrabit** [comment]
Thanks for notifying this, the call setFrame will be removed in the next update.
