### ISSUE TITLE
Failed detection of VST2xState headers in Cubase / Maschine projects

### ISSUE THREAD

**Issue by FelixPetriconi** [steinbergmedia/vst3_public_sdk#71]
During my work at Native Instruments on the Maschine 2 project we received the complaint from a customer that a Cubase project from 2017 using Maschine version 2.6 failed to open correctly with the latest Cubase + Maschine version.

We investigated that problem and found an issue in the VST3::tryVst2StateLoad() function at this [location](https://github.com/steinbergmedia/vst3_public_sdk/blob/master/source/vst/utility/vst2persistence.cpp#L521).
The deserialised value of numPrograms within the customers stored project is zero and so the mentioned functions returns an empty optional. Based on the information that there is no VST2 header we assume then in Maschine that this data stream is from a VST3 plugin. The following deserialisation of the Maschine data fails because it reads the binary stream of the VST2 header instead and the customer has a broken project.

We are able to reproduce this problem with the latest version of Cubase and Maschine:
- hide the installed Maschine VST3 plugin
- create a project with the VST2 plugin, load one of the Maschine library datasets and ensure that there some note events in the lane.
- store the project and close Cubase
- bring back the hidden Maschine VST3 plugin
- open the stored project
The attempt to migrate from VST2 to VST3 fails and the Maschine plugin contains no data

We think that having a value for numPrograms of zero is a valid use case in case that the VST2xState has no programs but a valid chunk.

A PR proposing a fix is coming within the next minutes.

**Comment by scheffle** [comment]
Thanks. Will be fixed with the next release.
