### ISSUE TITLE
Linux: Plugin bundles with an extra dot in the name fail to load with the `Hosting::Module` class

### ISSUE THREAD

**Issue by emuell** [steinbergmedia/vst3_public_sdk#73]
When loading a plugin SO using the Hosting::Module class from the VST3 SDK, and the plugin bundle path contains an extra dot in the name: e.g. `Boomer V1.0 bla.vst3` it fails to load. It tries to load the wrong SO file.

After it quick check, it seems that this is caused by:

https://github.com/steinbergmedia/vst3_public_sdk/blob/3fce096d6ee575479753f1aab23033d2e2ffdc6e/source/vst/hosting/module_linux.cpp#L170

Which simply should be 
```stem += ".so";```

This originally got reported here:
https://forum.renoise.com/t/linux-vst3-plugins-with-dots-in-so-name-fail-to-scan-e-g-waveshell1-vst3-15-0-x64-vst3/74085

**Comment by ygrabit** [comment]
thanks, this will be fixed in the next update...

**Comment by scheffle** [comment]
We have now fixed this with VST 3.7.13
