### ISSUE TITLE
AGain should provide the root unit.

### ISSUE THREAD

**Issue by hotwatermorning** [steinbergmedia/vst3_public_sdk#8]
https://github.com/steinbergmedia/vst3_public_sdk/blob/a502e2f4066bffb9aed13e071715b66235f59aba/samples/vst/again/source/againcontroller.cpp#L136-L143

Hi,

The VST3 SDK document says,

> The root unit is the component itself, so getUnitCount must return 1 at least.
> The root unit id has to be 0 (kRootUnitId).

(in the `IUnitInfo Class Reference` page)

> The root unit of this hierarchy is always present (explicit or implicit) and has ID '0'. A Plug-in that 
 does not define any further units simply consist of unit '0'.

(in the `Units` page)

But AGain sample does not provide the root unit if a developer does not want to use the programListId.

I suppose that these lines should not be commented out to meet IUnitInfo specification.
(and I suppose `validator` should test that a plugin provides the root unit.)

Thank you.

**Comment by hotwatermorning** [comment]
Could it be possible that a plugin can provide the root unit just as a hierarchy and there's no need to provide a UnitInfo of the root unit when a plugin provides child units?
(Is this the meaning of `implicit`?)

**Comment by scheffle** [comment]
The root unit is the plug-in itself. If you don't have a program list you don't need to setup the root unit.
